apiVersion: v1
kind: Service
metadata:
  name: clb-usermgmt-restapp-service
  labels: 
    app: usermgmt-restapp
spec:
  type: LoadBalancer # Bydefault it will create Classic Load Balancer.
  selector:
    app: usermgmt-restapp
  ports: 
    - port: 80
      targetPort: 8095