apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-mysql-pvc
spec:
  resources:
    requests:
      storage: 4Gi
  accessModes:
    - ReadWriteOnce
    # storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  storageClassName: ebs-sc

