# team-a-monitoring-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: team-a-monitoring
  namespace: team-a
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: team-a-monitoring-role
  namespace: team-a
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: team-a-monitoring-binding
  namespace: team-a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: team-a-monitoring-role
subjects:
  - kind: ServiceAccount
    name: team-a-monitoring
    namespace: team-a
