apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server

# By default, the Argo CD API server is not exposed with an external IP. 
# To access the API server, choose one of the following techniques to expose the Argo CD API server:

# kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'
# The patch command only changes the type.

# You can retrieve this External IP with:
# kubectl get svc argocd-server -n argocd -o=jsonpath='{.status.loadBalancer.ingress[0].ip}'

# OR You can port forward without exposing argocd api server
# kubectl port-forward svc/argocd-server -n argocd 8080:443
# Accessible by localhost:8080.



# Retrive Argocd Creds 
# argocd admin initial-password -n argocd
