apiVersion: v1
kind: Service
metadata:
  name: nlb-usermgmt-restapp-service
  labels: 
    app: usermgmt-restapp
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb # It will create Network LB.
spec:
  type: LoadBalancer # Bydefault it will create Classic Load Balancer.
  selector:
    app: usermgmt-restapp
  ports: 
    - port: 80
      targetPort: 8095