apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-hello-c
    image: nginxdemos/hello
    ports:
    - containerPort: 80

---

# Service.yml

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx        # must match pod label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # to get public access

